#!/usr/bin/python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.colors import LogNorm
import numpy, time
import peakutils
from astropy.io import fits
from scipy.ndimage import morphology as morph
from scipy.ndimage import filters
import os
from scipy import interpolate
import progressbar
from time import sleep
from ccdproc import  cosmicray_lacosmic
import copy
import sys
import ConfigParser
from os.path import expanduser
home = expanduser("~")

#Parse the config parameters
Config=ConfigParser.ConfigParser()
Config.read(home+'/'+'hesp.config')
objname=Config.get('Headers','objname')
objtype=Config.get('Headers','objtype')
reseltype=Config.get('Headers','reseltype')
dateobs=Config.get('Headers','dateobs')
exptime=Config.get('Headers','exptime')
reselkeylow=Config.get('Keys','reselkeylow')
reselkeyhigh=Config.get('Keys','reselkeyhigh')
biaskey=Config.get('Keys','biaskey')
flatkey=Config.get('Keys','flatkey')
calibkey=Config.get('Keys','calibkey')
objectkey=Config.get('Keys','objectkey')
fits_index=int(Config.get('Fits','index'))
binsize=float(Config.get('Extraction','binsize'))
binres=float(Config.get('Extraction','binres'))
path=Config.get('Config','path')


fig = plt.figure(1)

fl=sys.argv[1]
hdu=fits.open(fl)
scidata=hdu[0].data

if sys.argv[2]=='low':
	trfl = open(path+'lowresfibre1.trace', 'r')
else:
	trfl = open(path+'highresfibre1.trace', 'r')	
content=trfl.readlines()
p=[0,0,0]
for l in content:
 sl=l.split(" ")
 p[0]=float(sl[0])
 p[1]=float(sl[2])
 p[2]=float(sl[4])
 scatfity=[]
 scatfitx=[]
 for x0 in range(0,4095,1):
  y0=p[0]*x0**2+p[1]*x0+p[2]
  scatfity=numpy.append(scatfity,y0)
  scatfitx=numpy.append(scatfitx,x0) 	    
 plt.plot(scatfitx,scatfity,color='red')
 
if sys.argv[2]=='low':
	trfl = open(path+'lowresfibre2.trace', 'r')
else:
	trfl = open(path+'highresfibre2.trace', 'r')	
content=trfl.readlines()

for l in content:
 sl=l.split(" ")
 p[0]=float(sl[0])
 p[1]=float(sl[2])
 p[2]=float(sl[4])
 scatfity=[]
 scatfitx=[]
 for x0 in range(0,4095,1):
  y0=p[0]*x0**2+p[1]*x0+p[2]
  scatfity=numpy.append(scatfity,y0)
  scatfitx=numpy.append(scatfitx,x0) 	    
 plt.plot(scatfitx,scatfity,color='blue') 
 

plt.imshow(scidata, cmap=cm.gray_r, origin='lower', norm=LogNorm())
plt.show()
